[package]
name = "letterboxed_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
env_logger = "0.11.5"
log = "0.4.22"
pathfinding = "4.11.0"
trie-rs = "0.4.2"

[[bench]]
name = "solver_benchmark"
harness = false
